config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'games#index'
  resources :games do
    collection do
      get :search
    end
    resources :reviews
  end
  resources :videogames
  resources :pcgame
  resources :socialgame
   get 'games/:id/destroy' => 'games#destroy'
   resources :users
   get 'users/users/:id' => 'users#listofposts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :reviews
  has_many :pcgames
  has_many :videogames
  validates :image, :name, :platform, :genre, :text, presence: true
  validates :user_id, presence: true

  def review_average
    reviews.average(:rate).round if reviews.present?
  end
end

app/models/pcgame.rb
class Pcgame < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :reviews
  has_many :videogames
  has_many :socialgames
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :game
  belongs_to :user
  has_many :pcgames
  has_many :videogames
  has_many :socialgames
  validates :nickname, :rate, :title, :review, presence: true
end

app/models/socialgame.rb
class Socialgame < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :reviews
  has_many :pcgames
  has_many :videogames
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games
  has_many :reviews
  has_many :pcgames
  has_many :videogames
  has_many :socialgames
  validates :nickname, :email, :password, :password_confirmation, presence: true
end

app/models/videogame.rb
class Videogame < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :reviews
  has_many :socialgames
  has_many :pcgames
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_games, only: %i[show destroy edit update]

  def index
    @games = Game.all
    @games = Game.order("created_at").limit(26)
  end

  def new
    @games = Game.new
  end

  def create
    @games = Game.create(game_params)
    if @games.save
      flash[:success] = 'アイテムを登録しました'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @reviews = @games.reviews.order('created_at DESC').limit(10).page(params[:page]).per(26)
    @review = @games.reviews.build
  end

  def destroy
    if @games.user_id == current_user.id
      flash[:danger] = 'アイテムを削除しました'
      @games.destroy
      redirect_to root_path
    end  
  end

  def edit
  end

  def update
    if @games.user_id == current_user.id
      @games.update(set_game)
      if @games.save
        flash[:success] = 'アイテムを更新しました'
        redirect_to root_path
      else
        render :edit
      end
    end  
  end

  private

  def game_params
    params.require(:game).permit(:image, :name, :platform, :genre, :text).merge(user_id: current_user.id)
  end

  def set_game
    params.permit(:image, :name, :platform, :genre, :text)
  end

  def set_games
    @games = Game.find(params[:id])
  end


  def move_to_index 
    redirect_to action: :index unless
    user_signed_in?
  end 
end

app/controllers/pcgame_controller.rb
class PcgameController < ApplicationController
  
  def index
  end

  def show
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  layout 'review_site'
  before_action :ranking
  def ranking
    product_ids = Review.group(:game_id).order('count_game_id DESC').limit(5).count(:game_id).keys
    @ranking = product_ids.map { |id| Game.find(id) }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def create
    @reviews = Review.create(create_params)
    if @reviews.save
      flash[:success] = 'レビューを投稿しました'
      redirect_to root_path
    else
      flash[:danger] = 'レビューの投稿に失敗しました、ニックネーム、タイトル、レビューを記入したか確認してください'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @reviews = Review.find_by(params[:id]).destroy
    flash[:danger] = 'レビューを削除しました'
    redirect_back(fallback_location: root_path)
  end

  private
  def create_params
    params.require(:review).permit(:nickname, :rate, :title, :review).merge(game_id: params[:game_id], user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
  end

  def listofposts
    @games = Game.where(user_id: current_user.id).page(params[:page]).per(50).order('created_at DESC')
    @nickname = current_user.nickname
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gameposts_helper.rb
module GamepostsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pcgame_helper.rb
module PcgameHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/socialgame_helper.rb
module SocialgameHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videogames_helper.rb
module VideogamesHelper
end

app/views/layouts/_error_messages.html.haml
- if model.errors.any?
  .alert.alert-warning
    %ul
      - model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title Gamepost
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  = render 'shared/header'
  = yield
  = render 'shared/footer'

app/views/shared/_flash.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/shared/_footer.html.haml
%footer
  .footer-content
    .content-h
      .row-h
        .footer-logo-box
          .footer-logo
            = link_to 'ゲームソフト投稿サイト', root_path
          %p
            %small © 2020. All Rights Reserved.
        .footer-box01
          %ul
            %li
              = link_to 'トップページ', root_path
        .footer-box02
          %ul
            %li= link_to '新規投稿画面', new_game_path
            %li= link_to 'ビデオゲーム一覧へ', videogames_path
        .footer-box03
          %ul
            %li

app/views/shared/_header.html.haml
%header.header
  .header__logo
    .game__logo
      %h1.grid
        %a{:href => "/"} ゲームソフト投稿サイト
      %span.nav_toggle
        %i
        %i
        %i
      %nav.nav
        %ul.nav_menu_ul
          %li.nav_menu_li 
            = link_to "\uf015　ホーム", root_path, class: 'fa'
          %li.nav_menu_li
            = link_to "テレビゲーム", videogames_path, class: 'fa'
          %li.nav_menu_li
            = link_to "PCゲーム", pcgame_index_path, class: 'fa'
          %li.nav_menu_li
            = link_to "ソーシャルゲーム", socialgame_index_path, class: 'fa'
      .form-group
        = search_form_for @search, url: search_games_path do |f|
          = f.text_field :name_cont ,placeholder: '検索するテキストを入力...'
          = f.submit ("検索") , class: 'btns'
      - if user_signed_in?
        .user_nav
          %ul#menu
            %li
              = current_user.nickname
              %ul
                %li
                  %a{:href => "users/#{current_user.id}"} マイページ
                %li= link_to "ログアウト", destroy_user_session_path, method: :delete
          %a.post-h{:href => "/games/new"} 投稿する
      - else
        .grid-6
          = link_to "\uf2f6 ログイン", new_user_session_path, class: 'post fa'
          = link_to "\uf234 新規登録", new_user_registration_path, class: 'posts fa'
.header.container
  = render partial: 'shared/flash'