config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'games#index'
  resources :games do
    collection do
      get :search
    end
    resources :reviews
  end
  resources :videogames
  resources :pcgame
  resources :socialgame
   get 'games/:id/destroy' => 'games#destroy'
   resources :users
   get 'users/users/:id' => 'users#listofposts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :reviews
  has_many :pcgames
  has_many :videogames
  validates :image, :name, :platform, :genre, :text, presence: true
  validates :user_id, presence: true

  def review_average
    reviews.average(:rate).round if reviews.present?
  end
end

app/models/pcgame.rb
class Pcgame < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :reviews
  has_many :videogames
  has_many :socialgames
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :game
  belongs_to :user
  has_many :pcgames
  has_many :videogames
  has_many :socialgames
  validates :nickname, :rate, :title, :review, presence: true
end

app/models/socialgame.rb
class Socialgame < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :reviews
  has_many :pcgames
  has_many :videogames
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games
  has_many :reviews
  has_many :pcgames
  has_many :videogames
  has_many :socialgames
  validates :nickname, :email, :password, :password_confirmation, presence: true
end

app/models/videogame.rb
class Videogame < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :reviews
  has_many :socialgames
  has_many :pcgames
end

app/controllers/gameposts_controller.rb
class GamepostsController < ApplicationController
  before_action :move_to_index, except: %i[index show]

  def index
    @games = Game.all
    @games = Game.order('created_at DESC').page(params[:page]).per(50)
  end

  def new
    @games = Game.new
  end

  def create
    @games = Game.create(game_params)
    if @games.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @games = Game.find(params[:id])
    @reviews = Game.where(params[:id])
    @reviews = Review.order('created_at DESC').limit(10)
  end

  def destroy
    @games = Game.find(params[:id])
    @games.destroy if @games.user_id == current_user.id
  end

  def edit
    @games = Game.find(params[:id])
  end

  def update
    @games = Game.find(params[:id])
    if @games.user_id == current_user.id
      @games.update(set_game)
      if @games.save
        redirect_to root_path
      else
        render :edit
      end
    end
  end

  private

  def game_params
    params.require(:game).permit(:image, :name, :platform, :genre, :text).merge(user_id: current_user.id)
  end

  def set_game
    params.permit(:image, :name, :platform, :genre, :text)
  end

  def move_to_index
    redirect_to action: :index unless
    user_signed_in?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_games, only: %i[show destroy edit update]

  def index
    @games = Game.all
    @games = Game.order("created_at").limit(26)
  end

  def new
    @games = Game.new
  end

  def create
    @games = Game.create(game_params)
    if @games.save
      flash[:success] = 'アイテムを登録しました'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @reviews = @games.reviews.order('created_at DESC').limit(10).page(params[:page]).per(26)
    @review = @games.reviews.build
  end

  def destroy
    if @games.user_id == current_user.id
      flash[:danger] = 'アイテムを削除しました'
      @games.destroy
      redirect_to root_path
    end  
  end

  def edit
  end

  def update
    if @games.user_id == current_user.id
      @games.update(set_game)
      if @games.save
        flash[:success] = 'アイテムを更新しました'
        redirect_to root_path
      else
        render :edit
      end
    end  
  end

  private

  def game_params
    params.require(:game).permit(:image, :name, :platform, :genre, :text).merge(user_id: current_user.id)
  end

  def set_game
    params.permit(:image, :name, :platform, :genre, :text)
  end

  def set_games
    @games = Game.find(params[:id])
  end


  def move_to_index 
    redirect_to action: :index unless
    user_signed_in?
  end 
end

app/controllers/pcgame_controller.rb
class PcgameController < ApplicationController
  
  def index
  end

  def show
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  layout 'review_site'
  before_action :ranking
  def ranking
    product_ids = Review.group(:game_id).order('count_game_id DESC').limit(5).count(:game_id).keys
    @ranking = product_ids.map { |id| Game.find(id) }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def create
    @reviews = Review.create(create_params)
    if @reviews.save
      flash[:success] = 'レビューを投稿しました'
      redirect_to root_path
    else
      flash[:danger] = 'レビューの投稿に失敗しました、ニックネーム、タイトル、レビューを記入したか確認してください'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @reviews = Review.find_by(params[:id]).destroy
    flash[:danger] = 'レビューを削除しました'
    redirect_back(fallback_location: root_path)
  end

  private
  def create_params
    params.require(:review).permit(:nickname, :rate, :title, :review).merge(game_id: params[:game_id], user_id: current_user.id)
  end

end

app/controllers/socialgame_controller.rb
class SocialgameController < ApplicationController
  
  def index
  end

  def show
  end

  def destroy
  end

  def edit
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
  end

  def listofposts
    @games = Game.where(user_id: current_user.id).page(params[:page]).per(50).order('created_at DESC')
    @nickname = current_user.nickname
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gameposts_helper.rb
module GamepostsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pcgame_helper.rb
module PcgameHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/socialgame_helper.rb
module SocialgameHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videogames_helper.rb
module VideogamesHelper
end

app/views/gameposts/_Videogamesoftware.html.haml
%main.content
  .top-content
    .content-box
      .card
        - if @search_products
          - render partial: 'gameposts/games', collection: @search_products
        - else
          - render partial: 'gameposts/games', collection: @games
        - @games.each do |game|
          .box
            %a.links{:href => "/gameposts/#{game.id}"}
              %img.content_post{:src => "#{game.image}"}/
            %p.name-g= (game.name)
      %div
      %footer
        = paginate(@games)

app/views/gameposts/destroy.html.haml
.contents-row
  .success
    %h3.destroy
      削除が完了しました。
    %a.btn{:href => "/gameposts"} 投稿一覧へ戻る

app/views/gameposts/edit.html.haml
.contents-row
  .container
    = form_tag("/gameposts/#{@games.id}",method: :patch, multipart: :true) do
      %h3 投稿する
      %img.img-h{:src => "#{@games.image}"}/
      %input.img{:name => "image", :type => "file"}/
      %h3.game ゲーム名
      %input.name{:name => "name", :placeholder => "ゲーム名", :type => "text", :value => "#{@games.name}"}/
      %h3 platform
      %input.name{:name => "platform", :placeholder => "platform", :type => "text", :value => "#{@games.platform}"}/
      %h3 genre
      %input.name{:name => "genre", :placeholder => "genre", :type => "text", :value => "#{@games.genre}"}/
      %h3 ゲームの説明文
      %textarea.text{:cols => "21", :name => "text", :placeholder => "ゲームの説明文を入力してください。168文字まで", :wrap => 'hard'}= @games.text
      .button_wrapper
        %input.btn{:type => "submit", :value => "変更する"}/

app/views/gameposts/new.html.haml
.contents-row-h
  .container-h
    = form_for @games, url: gameposts_path, method: :post, remote: false do |f|
      = render 'layouts/error_messages', model: f.object
      %h3 投稿する
      = f.label :image, '画像ファイル'
      = f.file_field :image, class:'img-g'
      %h3.game ゲーム名
      = f.text_field :name, class:'name-h', placeholder: 'ゲーム名'
      %h3 プラットフォーム
      = f.text_field :platform, class:'name-h', placeholder: 'platform'
      %h3 ジャンル
      = f.text_field :genre, class:'name-h', placeholder: 'genre'
      %h3 ゲームの説明文
      = f.text_area :text, class: 'text-h', placeholder: 'ゲームの説明文を入力してください。', wrap: 'hard'
      = f.submit '投稿', class: 'button_wrapper-h'

app/views/gameposts/search.html.haml
%main.content
  .top-content
    .content-box
      .card
        - @search_products.each do |game|
          .box
            %a.links{:href => "/gameposts/#{game.id}"}
              %img.content_post{:src => "#{game.image}"}/
            %p.name-g= (game.name)
      %div
      

app/views/gameposts/show.html.haml
%section.product-container
  .container-box
    %h1.item-name
      = @games.name
    .item-container
      %table.item-table
        %tbody
          %tr
            %th プラットフォーム
            %td= @games.platform
          %tr
            %th ジャンル
            %td= @games.genre
          %tr
            %th.game-text ゲームの説明文
            %td.text-description= @games.text
      .item-imges
        %img.content_post{:src => "#{@games.image}"}/
      = link_to 'レビュー投稿画面', '/gameposts/:gamepost_id/reviews/new', class: 'reviewpostingscreen'
- if user_signed_in? && current_user.id == @games.user_id
  .container-box2
    .item-box
      %a.btn-default.btn-red{:href => "#{@games.id}/edit"} 編集
    %button.btn-default.btn-gray
      %a{:href => "#{@games.id}/destroy"} 削除
.content-box3
  %h4 レビュー一覧
  .h-row
    - if @reviews
      - @reviews.each do |review|
        .a-row
          .review-content
            %span.profile-nickname
              = review.nickname
          .g-row
            %i{:id => "star-rate-#{review.id}"}
            :javascript
              $('#star-rate-#{review.id}').raty({
                size: 36,
                starOff:  '#{asset_path('star-off.png')}',
                starOn : '#{asset_path('star-on.png')}',
                starHalf: '#{asset_path('star-half.png')}',
                half: true,
                readOnly: true,
                score: '#{review.rate}',
              });
            %span.h-letter-space
              = review.title
            %p
              = review.created_at.to_s(:datetime_jp)
          .reviewtext
            %span
              = review.review

app/views/reviews/_new_post.html.haml
.review
  %h1.review-h レビュー投稿
  = form_with(model: [@games, @review], local: true) do |f|
    = render 'layouts/error_messages', model: f.object
    .nickname
      = f.label :nickname, style: { 'margin-right' => 10 }
      = f.text_field :nickname, placeholder: 'ニックネーム', value: ''
    .evaluation
      = f.label :評価, style: { 'margin-right' => 8 }, value: '評価5段階'
      = f.number_field :rate, placeholder: '評価', value: 1, max: 5, min: 1, html: { class: "search__query", style: 'text-align: right;' }
    .title
      = f.label :title, style: { 'margin-right' => 10 }
      = f.text_field :title, placeholder: 'タイトル', value: ''
    .review-text
      = f.text_area :review, placeholder: 'ゲームの感想をお書き下さい。', style: 'width: 25%; height: 150px; border: 2px solid skyblue;'
    .row
      .col10.push1
        = button_tag type: "submit", class: "btn btn--block" do
          投稿する
          %i.fa.fa-arrow-right
          

app/views/reviews/_posts.html.haml
.content-box3
  %h4 レビュー一覧
  .h-row
    - if @reviews
      - @reviews.each do |review|
        .a-row
          .review-content
            %span.profile-nickname
              = review.nickname
          .g-row
            %i{:id => "star-rate-#{review.id}"}
            :javascript
              $('#star-rate-#{review.id}').raty({
                size: 36,
                starOff:  '#{asset_path('star-off.png')}',
                starOn : '#{asset_path('star-on.png')}',
                starHalf: '#{asset_path('star-half.png')}',
                half: true,
                readOnly: true,
                score: '#{review.rate}',
              });
            %span.h-letter-space
              = review.title
            %p 
              = review.created_at.to_s(:datetime_jp)
          .reviewtext
            %span
              = review.review
          .reviewedit
          - if user_signed_in? && current_user == @games.user
            = link_to 'レビューを削除', game_review_path(@reviews), method: :delete

app/views/reviews/new.html.haml
.review
  %h1.review-h レビュー投稿
  = form_for [@reviews], url: gamepost_reviews_path do |f|
    = render 'layouts/error_messages', model: f.object
    .nickname
      = f.label :nickname, style: { 'margin-right' => 10 }
      = f.text_field :nickname, placeholder: 'ニックネーム', value: ''
    .evaluation
      = f.label :評価, style: { 'margin-right' => 8 }, value: '評価5段階'
      = f.number_field :rate, placeholder: '評価', value: 1, max: 5, min: 1, html: { class: "search__query", style: 'text-align: right;' }
    .title
      = f.label :title, style: { 'margin-right' => 10 }
      = f.text_field :title, placeholder: 'タイトル', value: ''
    .review-text
      = f.text_area :review, placeholder: 'ゲームの感想をお書き下さい。', style: 'width: 25%; height: 150px; border: 2px solid skyblue;'
    .row
      .col10.push1
        = button_tag type: "submit", class: "btn btn--block" do
          投稿する
          %i.fa.fa-arrow-right